# Generated by Django 4.2.2 on 2023-09-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_alter_hash_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('decompressed_size', models.PositiveIntegerField(default=0)),
                ('compressed_size', models.PositiveIntegerField(default=0)),
                ('hashes', models.ManyToManyField(related_name='hashes', to='files.hash')),
                ('onetime_hashes', models.ManyToManyField(related_name='onetime_hashes', to='files.hash')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.user')),
            ],
        ),
    ]
