# Generated by Django 4.2.2 on 2023-09-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_hash_size_after_hash_size_before'),
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashes',
            field=models.ManyToManyField(blank=True, related_name='hashes', to='files.hash'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onetime_hashes',
            field=models.ManyToManyField(blank=True, related_name='onetime_hashes', to='files.hash'),
        ),
    ]
