# Generated by Django 4.2.5 on 2023-09-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compressed_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='decompressed_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
