# Generated by Django 4.2.5 on 2023-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_alter_user_hashes_alter_user_onetime_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.IntegerField(default=0),
        ),
    ]
