# Generated by Django 4.2.5 on 2023-10-25 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0003_user_lat_user_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='long',
        ),
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 25, 20, 20, 49, 875521, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
