# Generated by Django 4.2.5 on 2023-10-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0004_remove_user_lat_remove_user_long_session_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
