# Generated by Django 4.2.2 on 2023-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_hash_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCrossFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
    ]
