# Generated by Django 4.2.2 on 2023-09-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_tempcrossfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='size_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hash',
            name='size_before',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
