# Generated by Django 4.2.2 on 2023-09-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_hash_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hash',
            old_name='size_after',
            new_name='compressed_size',
        ),
        migrations.RenameField(
            model_name='hash',
            old_name='size_before',
            new_name='decompressed_size',
        ),
    ]
