# Generated by Django 4.2.2 on 2023-09-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_rename_size_after_hash_compressed_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='compressed_value',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hash',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
